### ISSUE TITLE
cyclic dependency with testtools

### ISSUE THREAD

**Issue by 0-wiz-0** [testing-cabal/testscenarios#4]
testscenarios depends on testtools.
However, as of 1.9.0, testtools (test-)depends on testscenarios.
This is a problem for package managers where usually only one of the two is allowed.

**Comment by rbtcollins** [comment]
The dependency is a runtime, not a build time dependency, and most package managers have no issues with with that.

**Comment by 0-wiz-0** [comment]
pkgsrc does have a problem with that.

**Comment by rbtcollins** [comment]
I suggest introducing a thunk virtual package in pkgsrc:
testtools -> testtools', testscenarios'
testscenarios -> testtools', testscenarios'

Where testtools' is the upstream package, and testtools is what the users request.

**Comment by 0-wiz-0** [comment]
If, from a user point of view, you cannot get one without the other, why not merge them?

**Comment by rbtcollins** [comment]
You totally can get just one using the native Python tooling. You're the one reporting a cyclic dependency which doesn't affect other platforms. https://github.com/testing-cabal/testtools/blob/master/requirements.txt doesn't include testscenarios.

**Comment by rbtcollins** [comment]
Evidence installing testtools doesn't install testscenarios:
```py -m venv test
(test) py -m pip install testresources
Collecting testresources
  Using cached https://files.pythonhosted.org/packages/45/4d/79a9a1f71de22fbc6c6433ac135f68d005de72fbe73e2137d2e77da9252c/testresources-2.0.1-py2.py3-none-any.whl
Collecting pbr>=1.8 (from testresources)
  Downloading https://files.pythonhosted.org/packages/e0/27/a913b227c9053472ea7dda33e409a1e748e50cdd208a955f3d6a20e9a875/pbr-5.3.0-py2.py3-none-any.whl (108kB)
    100% |████████████████████████████████| 112kB 1.6MB/s
Installing collected packages: pbr, testresources
Successfully installed pbr-5.3.0 testresources-2.0.1
```

-> its not a cyclic dependency.

Your testtools package should not depend on testscenarios. At build time it should use it to run its own tests, but not at install time.

As for how you manage the cycle there - that is surely the same as how you manage the cycle of gcc requiring a compiler to build, or bash requiring a compiler or any of these packages: you use a previous binary. Cycles exist *everywhere* in the stack, because absolutely nothing is bootstrapped from machinecode, not for oh 30 years.

If there is something reasonable and actionable here we'll do it, but currently it doesn't look like thats the case.

**Comment by 0-wiz-0** [comment]
At least some packaging systems like to stratify their build tree when building from scratch, and that includes the build/test dependencies; there are not two separate runs for building the software and testing it. This is not possible with testscenarios/testtools since for testing.
I see that you don't consider this an issue and don't want to change anything about this, which is a pity. I reported this because it's a rare occurrence, most other programs do not have this problem.

**Comment by rbtcollins** [comment]
I do appreciate the thought and consideration. To sum up -

 - testscenarios is usable by folk not using testtools; having it be a separate dedicated library makes sense
 - upstream development and testing is not hampered by this issue - testtools builds (source -> wheel) don't require testscenarios at all; and testscenarios builds (source -> wheel) similarly only require compilation. 
 - development of both tools happens to require both tools, but this is pretty unrelated, by analogy its just that they are both useful things - developing gcc requires both make and gcc, though admittedly these packages are closer together in a dependency graph

I disagree with you on the frequency of the problem though; in some domains of software - that of build tooling - the problem is actually very common : everything that make depends on to build (shell, gcc, binutils, moreutils, libc) forms a cycle. Every build tool in every language that itself uses things from its own ecosystem has the same circular property; and test libraries are fundamentally a form of build tool, isolated to the QA function.

And it actually makes a lot of sense to encourage this: our tooling should be good, and should not be limited to being built without the ability to other libraries. It is better for our ecosystems to engineer to support circular dependencies, than to engineer our dependencies to avoid them.

https://wiki.debian.org/BuildProfileSpec - is the Debian design for dealing with this in the general case, allowing fully automated two-pass builds, one without testing to get something up that permits the second pass to run with the full test suite; perhaps that would be a good design to consider for pkgsrc.

**Comment by 0-wiz-0** [comment]
We obviously come from different worlds :)
NetBSD builds itself on any system that provides a good enough shell and compiler. Then you get a running system include sh, libc, compiler, make, X, full test suite, ...

pkgsrc assumes a minimal system as well, though it expects more tools than NetBSD itself.

**Comment by rbtcollins** [comment]
Perhaps yes :) Certainly my views have changed on this over the last 20 years :>.

So this - http://cvsweb.netbsd.org/bsdweb.cgi/src/tools/make/buildmake.sh.in?rev=1.12&content-type=text/x-cvsweb-markup&only_with_tag=MAIN - can be thought of as an exported static output from make right? In that you could imagine a mode in make where you compile a shell script rather than having it run interactively; that could be committed to VCS and used, and one still gets the desired properties, but with less to directly maintain.

Anyhow I agree that systems need to be able to do the bootstrap and run dance without manual intervention; and hope that we're not making things too much of an issue for you.
